
# This file configures the build and deployment settings for Netlify.

[build]
  command = "next build"
  publish = ".next"

[functions]
  # Configures the function associated with the specified API route.
  # This makes it available for scheduling.
  included_files = ["src/app/api/send-expiry-alerts/**"]

# Schedules the function to run at 9am, 3pm, and 9pm UTC every day.
[[plugins]]
package = "@netlify/plugin-functions-schedule"
  [plugins.inputs]
  schedules = [
    { cron = "0 9,15,21 * * *", function = "send-expiry-alerts" }
  ]
