
# This file configures the build and deployment settings for Netlify.

# Build settings for a Next.js application
[build]
  command = "next build"
  publish = ".next"

# Configuration for Netlify Functions, including scheduled functions.
[functions]
  # Specifies the directory where Netlify will find the serverless functions.
  # For Next.js App Router, API routes are automatically discovered.
  
  # Schedules the 'send-expiry-alerts' function to run daily at 9:00 AM UTC.
  [functions.schedule]
    "send-expiry-alerts" = "0 9 * * *"

