
# This file configures the build and deployment settings for Netlify.

# Build settings for a Next.js application
[build]
  command = "next build"
  publish = ".next"

# Schedules the API route at /api/send-expiry-alerts to run daily at 9:00 AM UTC.
[functions."send-expiry-alerts"]
  schedule = "0 9 * * *"
